name: CI
on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    container: node:16.10.0
    steps:
      - uses: actions/checkout@v3
      - name: retrieve packages
        run: npm install
      - name: check linter
        run: npm run lint
      - name: check compile
        run: npm run build